# Generated by Django 3.1.3 on 2020-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='image',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
